namespace: vmware
name: vmware_rest
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description:
license: null
license_file: LICENSE
tags:
  - cloud
  - vmware
  - virtualization
dependencies: {}
repository: https://github.com/ansible-collections/vmware_rest.git
homepage: https://github.com/ansible-collections/vmware_rest
issues: https://github.com/ansible-collections/vmware_rest/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
