---
namespace: vmware
name: vmware_rest
readme: README.md
version: "4.8.0"
authors:
  - Ansible (https://github.com/ansible)
description: VMware collection for Ansible
license_file: LICENSE
tags:
  - cloud
  - vmware
  - virtualization
dependencies:
  cloud.common: ">=4.1.0,<5.0.0"
repository: https://github.com/ansible-collections/vmware.vmware_rest
homepage: https://github.com/ansible-collections/vmware.vmware_rest
issues: https://github.com/ansible-collections/vmware.vmware_rest/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
build_ignore:
  - config/*
