---
namespace: vmware
name: vmware_rest
readme: README.md
version: "4.7.0"
authors:
  - Ansible (https://github.com/ansible)
description: VMware collection for Ansible
license_file: LICENSE
tags:
  - cloud
  - vmware
  - virtualization
dependencies:
  # pinned at 4.0.0 because higher versions break the lookup plugins
  cloud.common: ">=3.0.0,<=4.0.0"
repository: https://github.com/ansible-collections/vmware.vmware_rest
homepage: https://github.com/ansible-collections/vmware.vmware_rest
issues: https://github.com/ansible-collections/vmware.vmware_rest/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
build_ignore:
  - config/*
