namespace: ansible
name: vmware_rest
version: 1.0.0
readme: null
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: https://github.com/ansible-collections/vmware_rest.git
documentation: null
homepage: null
issues: null
