# SonarCloud project configuration for vmware.vmware_rest
# Complete documentation: https://docs.sonarqube.org/latest/analysis/analysis-parameters/

sonar.projectKey=ansible-collections_vmware.vmware_rest
sonar.organization=ansible-collections
sonar.sources=.
sonar.projectName=vmware.vmware_rest
sonar.python.coverage.reportPaths=coverage.xml

sonar.tests=tests/unit,tests/integration
sonar.python.version=3.12
sonar.newCode.referenceBranch=main

sonar.exclusions=tests/**,.tox/**


# rules to ignore
sonar.issue.ignore.multicriteria=e1
# dont require literals when creating empty sets, lists, or dicts
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S7498
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.py
