# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
---
blank_issues_enabled: true  # default: true
contact_links:
  - name: Ansible Code of Conduct
    url: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html?utm_medium=github&utm_source=issue_template_chooser_ansible_collections
    about: Be nice to other members of the community.
  - name: Community Discussions
    url: https://forum.ansible.com/tag/vmware
    about: The Ansible Forum is the best place to ask general questions and start discussions with the community.
  - name: Enterprise Support
    url: https://www.ansible.com/products/engine?utm_medium=github&utm_source=issue_template_chooser_ansible_collections
    about: Red Hat offers support for the Ansible Automation Platform, which includes certified content like this collection.
