---
name: Publish Collection Docs
concurrency:
  group: docs-push-${{ github.sha }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
      - stable-*
    tags:
      - "*"
  schedule:
    - cron: "0 12 * * *"

jobs:
  build-docs:
    permissions:
      contents: read
    name: Build Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@main
    with:
      init-lenient: false
      init-fail-on-error: true
      intersphinx-links: |
        ansible_devel:https://docs.ansible.com/ansible-core/devel/
      provide-link-targets: |
        ansible_collections.vmware.vmware.vcsa_settings_module

  publish-docs-gh-pages:
    # use to prevent running on forks
    if: github.repository == 'ansible-collections/vmware.vmware_rest'
    permissions:
      contents: write
      pages: write
      id-token: write
    needs: [build-docs]
    name: Publish Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-publish-gh-pages.yml@main
    with:
      artifact-name: ${{ needs.build-docs.outputs.artifact-name }}
      publish-gh-pages-branch: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
