# -*- coding: utf-8 -*-
# Copyright: (c) 2026, Ansible Project
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
# Reference scaffold for unit tests generated by the generate-unit-tests subagent.
# Output path: tests/unit/plugins/modules/test_<module_name>.py
# Run tests: make units UNIT_TARGETS='tests/unit/plugins/modules/test_<module_name>.py'
# See: .agents/subagents/generate-unit-tests.md

## Note to AI: Lines starting with ## are instructions — do not include them in the output file.
## Replace <PLACEHOLDER> values from the API spec, not from the module under test.


from __future__ import absolute_import, division, print_function

__metaclass__ = type

import json
import pytest
from unittest.mock import patch, MagicMock

from ansible_collections.vmware.vmware_rest.plugins.module_utils._client import (
    Response,
)
from ansible_collections.vmware.vmware_rest.plugins.modules import <MODULE_NAME> as module_under_test


class AnsibleExitJson(Exception):
    def __init__(self, kwargs):
        self.kwargs = kwargs


class AnsibleFailJson(Exception):
    def __init__(self, kwargs):
        self.kwargs = kwargs


def exit_json(*args, **kwargs):
    if args:
        kwargs.update(args[0])
    raise AnsibleExitJson(kwargs)


def fail_json(*args, **kwargs):
    if args:
        kwargs.update(args[0])
    raise AnsibleFailJson(kwargs)


def _response(status, body):
    ## Build a Response from API-spec-derived JSON (status + body from operation responses).
    data = json.dumps(body).encode("utf-8") if body is not None else b""
    return Response(status, data)


## Minimal connection params for prepare_argument_spec().
CONNECTION_PARAMS = {
    "vcenter_hostname": "vcenter.example.com",
    "vcenter_username": "admin",
    "vcenter_password": "secret",
    "vcenter_validate_certs": False,
    "vcenter_rest_log_file": None,
    "session_timeout": None,
}


@pytest.fixture
def mock_client():
    client = MagicMock()
    return client


@pytest.fixture
def module_args():
    return dict(CONNECTION_PARAMS)


def set_module_args(args):
    ## Merge connection params with scenario-specific module options.
    return {**CONNECTION_PARAMS, **args}


@patch.object(module_under_test, "AnsibleModule")
@patch.object(module_under_test.VmwareRestInfoModule, "_create_client")
def test_<SCENARIO_NAME>(mock_create_client, mock_ansible_module, mock_client, module_args):
    ## Example info-module test: LIST summaries from spec, then GET detail per MOID.
    mock_create_client.return_value = mock_client
    mock_module = MagicMock()
    mock_ansible_module.return_value = mock_module
    mock_module.params = set_module_args(module_args)

    ## Mock responses derived from API spec schemas and operation response codes.
    mock_client.get.side_effect = [
        _response(200, <LIST_BODY_FROM_SPEC>),
        _response(200, <GET_BODY_FROM_SPEC>),
    ]

    with pytest.raises(AnsibleExitJson) as exc:
        module_under_test.main()

    mock_module.exit_json.assert_called_once()
    result = exc.value.kwargs
    assert result == <EXPECTED_MODULE_RESULT_FROM_SPEC>
